### ISSUE TITLE
Importing LR2 (or other game) score database

### ISSUE THREAD

**Issue by Dolphinssss** [zardoru/raindrop#19] opened 2016-01-25 15:28 UTC
In reference to https://github.com/zardoru/raindrop/issues/18

Having the ability to import your scores from your local LR2 score database would be perfect for migration. Likewise with other games score databases (eg SM)

**Comment by zardoru** [comment] 2016-01-25 18:41
again, wrt using a LR2 score database this requires us to have knowledge of how it's laid out.

**Comment by Dolphinssss** [comment] 2016-04-15 17:00
Arras just sent me this image of the insides of an LR2 score database.
It's really self-explanatory how this db works.
Seems to be a normal MySQL database.

![](http://i.imgur.com/UEOCLG5.png)

**Comment by zardoru** [comment] 2016-11-08 08:21
lr2 uses MD5 hashes. raindrop uses SHA-256 hashes. by design.
the reliability of scores can not be certified and scores would be meaningless in any case as there's no intentions of emulating LR2.
closing.

**Closed by zardoru** 2016-11-08 08:21 UTC
Labels: enhancement
