### ISSUE TITLE
issues with using Rate

### ISSUE THREAD

**Issue by Ovnize** [zardoru/raindrop#57] opened 2016-10-12 11:33 UTC
scrolling speed doesn't scale properly (tested Mode and Constant but I'm pretty sure other speed classes do this too), and the timing windows are affected by the rate

**Comment by zardoru** [comment] 2016-10-12 23:40
Timing windows being affected by the rate is _technically_ by design.
As for scrolling speed, you'll have to elaborate.

**Comment by Ovnize** [comment] 2016-10-13 12:59
If I play something using Constant Speed with a target speed of 1400 at x1 and then play it again with the same exact settings except that the rate is now x2, the notes will scroll 2 times faster

**Comment by zardoru** [comment] 2016-10-13 15:04
I wouldn't exactly consider it an "issue", but I'll definitely change how it works.

**Comment by zardoru** [comment] 2016-11-08 08:17
the multiplier behaviour on rates has been changed. closing issue.

**Closed by zardoru** 2016-11-08 08:17 UTC
Labels: enhancement
